[package]
name = "data-formats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.73"
serde_test = "1.0.139"
